### ISSUE TITLE
enableHermes: true error

### ISSUE THREAD

**Issue by hungnq139** [mrousavy/react-native-multithreading#13]
When i run example with hermes on android app crash with error :

<img width="870" alt="Screen Shot 2021-04-23 at 10 15 50" src="https://user-images.githubusercontent.com/50257086/115813190-eef4eb00-a41c-11eb-8146-d8142331896c.png">

Thanks

**Comment by mrousavy** [comment]
Can you run with `enableHermes: false`? Remember to run `./gradlew clean` after changing that flag

**Comment by hungnq139** [comment]
do you fix it ? react-native-reanimated recommend enable it 😂

**Comment by mrousavy** [comment]
Reanimated (and rn-multithreading) should work with Hermes as well as with JSC, on my machine the example runs with both 🧐

**Comment by Lemon-King** [comment]
android/app/build.gradle
"implementation jscFlavor" is not defined under the if statement for enableHermes, for me I removed the if /else statement.

`    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }`

**Comment by hungnq139** [comment]
@Lemon-King  it same as enableHermes:false 😂

**Comment by hungnq139** [comment]
> Reanimated (and rn-multithreading) should work with Hermes as well as with JSC, on my machine the example runs with both 🧐

Thanks you ! I will tracking it

**Comment by 4yki** [comment]
@hungnq139 , did you resolve the issue on android ?
