### ISSUE TITLE
Android crashes on startup

### ISSUE THREAD

**Issue by 4yki** [mrousavy/react-native-multithreading#16]
Having issue with android. I've followed your setup guide https://github.com/mrousavy/react-native-multithreading/blob/master/SETUP.md

Logs:

```
2021-04-27 16:07:10.571 3681-3875/com.ossapp E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.ossapp, PID: 3681
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libjsc.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.reactnativemultithreading.MultithreadingModule.<clinit>(MultithreadingModule.java:26)
        at com.reactnativemultithreading.MultithreadingPackage.createNativeModules(MultithreadingPackage.java:17)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1347)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1318)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1240)
        at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1023)
        at java.lang.Thread.run(Thread.java:919)
```

Could you help? thx 

**System info**
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
    Memory: 1.79 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 29, 30
      Build Tools: 29.0.2, 29.0.3, 30.0.3
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:

**Comment by mrousavy** [comment]
Are you using Hermes or JSC?

**Comment by 4yki** [comment]
> Are you using Hermes or JSC?

Hermes.

**Comment by mrousavy** [comment]
Can you run the example app on android? I'll try to find out what went wrong on runtime creation

**Comment by 4yki** [comment]
so far can confirm, that with enableHermes: true,  my project and your example project crashes on start with the logs above. 
Saw that others also facing this issue:
https://github.com/mrousavy/react-native-multithreading/issues/13

it crashes on that line of code:
`System.loadLibrary("rnmultithreading");`

**Comment by mrousavy** [comment]
How did you find out that the error comes from that line? I'm pretty sure it's crashing here:
https://github.com/mrousavy/react-native-multithreading/blob/9d84b003d68017f424bc9c0f5e748feb8d90fa11/android/src/main/java/com/reactnativemultithreading/MultithreadingModule.java#L69-L105

**Comment by 4yki** [comment]
`at com.reactnativemultithreading.MultithreadingModule.<clinit>(MultithreadingModule.java:26)`
log is pointing to that piece of code :) any thoughts about reasons of crash ?

**Comment by mrousavy** [comment]
Oh, you're right! That's weird, I'll try to find out what's wrong here. Maybe the `build.gradle` configuration is wrong 🤔

**Comment by 4yki** [comment]
@mrousavy , any updates here?

**Comment by mrousavy** [comment]
Yes, I want to wait for [reanimated #1960](https://github.com/software-mansion/react-native-reanimated/pull/1960), because that changes quite a few things with how the runtime gets created.

**Comment by Szymon20000** [comment]
@mrousavy  I think the problem is in your CmakeLists.txt. https://github.com/mrousavy/react-native-multithreading/blob/master/android/CMakeLists.txt#L98 - Here you add a dependency to JSC. ReactNative provides libjsc.so only when you use JSC.

**Comment by mrousavy** [comment]
@Szymon20000 oh I see, wouldn't it fail at the build stage though?

**Comment by Szymon20000** [comment]
@mrousavy I think I know how to solve the problem. I've messaged you on slack.

**Comment by mrousavy** [comment]
@4yki with the help of @Szymon20000 I managed to decouple RNMultithreading from JSC. Can you try with version 1.1.0 and see if that fixed your issue?

**Comment by 4yki** [comment]
> @4yki with the help of @Szymon20000 I managed to decouple RNMultithreading from JSC. Can you try with version 1.1.0 and see if that fixed your issue?

Sure,  will check today. Thx

**Comment by 4yki** [comment]
ok! I can't reproduce crash anymore! Thx guys for your work!

**Comment by enahum** [comment]
I'm trying 1.1.1 with hermes enabled but getting the error trying to load `libjsc.so`

**Comment by nomi9995** [comment]
it is reproducing on `"react-native-reanimated": "^2.3.0-alpha.2"`

**Comment by DominickVale** [comment]
> it is reproducing on `"react-native-reanimated": "^2.3.0-alpha.2"` + `hermes` + `react-native-multithreading@1.1.1`

same thing but with react native 0.66 ^^^^
