### ISSUE TITLE
API calling is not supported in spawnThread.

### ISSUE THREAD

**Issue by nomi9995** [mrousavy/react-native-multithreading#19]
The API call is not supported in spawnThread yet. 

if we use `runOnJs` then we are unable to await `runOnUI `

if we make awaitable `runOnUI ` by your PR https://github.com/software-mansion/react-native-reanimated/pull/1884
then console.log not showing but showing native log and console.log complete block and runOnJS is unable to call API after above PR implementation

**Comment by mrousavy** [comment]
What does "API call" mean?

**Comment by nomi9995** [comment]
@mrousavy API call means call HTTP/HTTPS API call through `fetch` or `axios`

**Comment by mrousavy** [comment]
Isn't fetch async by nature? As in, the HTTP call does not block the JavaScript thread

**Comment by nomi9995** [comment]
`Axios/fetch` also use native code behind the scene. when I try to call `fetch/Axios` API from `spawnThread` then I am getting this error

```
Compiling JS failed: 448812:50:';' expected Buffer size 21370526 starts with: 766172205f5f42554e444c455f535441

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start

```

**Comment by mrousavy** [comment]
Right, but `fetch` is a polyfill in React Native which is not marked as a `'worklet'`, so you cannot directly call it.

**Comment by mrousavy** [comment]
You can only call it when it is either marked as `'worklet'`, or when it's a direct native function (no JS function body)

**Comment by nomi9995** [comment]
@mrousavy how can we add API calling support in worklet?

**Comment by mrousavy** [comment]
For that the API call (`fetch`) has to be a native host function. Mabye take a look at https://github.com/mrousavy/react-native-multithreading/issues/24 to get inspiration
