### ISSUE TITLE
com.reactnativemultithreading not exist

### ISSUE THREAD

**Issue by sindu12jun** [mrousavy/react-native-multithreading#25]
Hi, thanks for this great project!

I am having an issue now: com.reactnativemultithreading not exist, when running `yarn android`

Here's how I import the libs: 

```
import com.reactnativemultithreading.MultithreadingJSIModulePackage;
import com.facebook.react.bridge.JSIModulePackage;
```

I am using react-native@0.64.1, not using MMKV

**Comment by mrousavy** [comment]
Take a look at https://github.com/mrousavy/react-native-mmkv/issues/37 (use multithreading instead of MMKV) and see if that works for you

**Comment by sindu12jun** [comment]
it's working, thanks!
