### ISSUE TITLE
Calling external libraries from a worklet

### ISSUE THREAD

**Issue by gursesl** [mrousavy/react-native-multithreading#29]
More of a question than an issue. When using an external library such as lodash inside a worklet, why does the value come undefined?

```
// fib[0] = 0;
const lodashRandomNumber = _.random(1, 5);
console.log(`[lodashRandomNumber] ${lodashRandomNumber}`); // This will be undefined
fib[0] = lodashRandomNumber;
```

**Comment by mrousavy** [comment]
In the README under ["What's possible?"](https://github.com/mrousavy/react-native-multithreading#whats-possible) I have stated that functions that you want to call directly have to have the `'worklet'` directive at the top, which lodash's `random` function doesn't have. so you cannot directly call it inside a worklet.
