### ISSUE TITLE
[Question]: About `spawnThread's` thread name

### ISSUE THREAD

**Issue by myckhel** [mrousavy/react-native-multithreading#30]
Hello @mrousavy,
Thanks for this library

To my understanding, spawnThread runs function in `// custom thread` as you mentioned.
My Question:
- What is the name of the thread `spawnThread` is using?
- - if named, does it have a dedicated thread?
- - else does it create new thread for each functions?

**Comment by mrousavy** [comment]
The name of a thread is only a concept by Xcode/Android Studio. The Thread does not have a name, it's a normal C++ thread. It's a pool of 1 (for now), so the parallel thread is re-used.

**Comment by myckhel** [comment]
Okay Thanks for your answer.
